### PR TITLE
Fixing some errors and adding Redis via docker-compose

### PR DESCRIPTION
**Pull request by Dudu197**
New features:
  - Added docker-compose file for using Redis without needing to install it

Errors fixed:
  - Typo in error checking
  - Error while importing commands files on Windows
  - Updated some dependencies due vulnerabilities

### CODE REVIEW

**Comment by jack3898** [comment]
Hey Dudu197, thanks for the PR and sorry for the neglect I have given this bot over the past 5 months!

As there's clearly interest in wanting to sustain this bot, I think I need to start putting more work into it again. I will review/test your PR and give feedback ASAP!

Luckily, I know Docker and React well enough to take your contributions and confidently review them. How do you feel about me converting this project to TypeScript in the future as well?

I think I want to also get this bot using slash commands, which I know will be a task and half but it's the best way to do commands now so I think it's a must!

Again, thanks for the PR! 😁

**Comment by jack3898** [comment]
I will review the code hopefully tomorrow. :)

**Comment by Dudu197** [comment]
Wow, the Pull Request wasn't supposed to contains the react part, I'm sorry.
I'll create another Pull Request with the correct code.

Sorry for this.

**Comment by Dudu197** [comment]
BTW, this React part is for creating a Web interface so I can interact better with the bot while playing RPG with my friends.
I'm trying to use for some soundtracks and sound effects in the game, and I could quickly control these sound from the Web interface and sending commands to the bot via socket.

Feel free to talk with me if you want to make something similar.

**Comment by jack3898** [comment]
It's fine! That's an interesting concept, but not something I would add to this bot as it's a YouTube bot. However, a web interface is an idea that I would like to implement. To start with it would be nice to sign in with Google within the web interface, which will set up the YouTube API instead of environment variables slapped everywhere. Same with any other configs. :)

**Pull request closed without merging**
